### ISSUE TITLE
Response already sent

### ISSUE THREAD

**Issue by 1MiloAC** [3raphat/chatGPT-discord-bot#3]
The following code in chat.js will cause an error due to a response already being sent:

await interaction.deferReply({ content: "Let me think..." })

This is due to the code not being able to issue a second response after this one. 

**It is after commenting out this line of code that my other error message will occur. See #2 for more details.**

**Comment by thrxpt** [comment]
You can try to delete this line and edit `await interaction.editReply(...)` to `await interaction.reply(...)`
